### PR TITLE
Ewilliams

### PR DESCRIPTION
**Pull request by edwdev**
Please double check this looks OK

### CODE REVIEW

**Comment by penetal** [comment]
Ran Plan for project: `lab-atlantis` dir: `iac/mgmt/atlantis` workspace: `default`

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

~ module.atlantis.aws_alb_target_group.app
      health_check.0.matcher: "200" => "200-499"
Plan: 0 to add, 1 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p lab-atlantis`
* :put_litter_in_its_place: To **delete** this plan click [here](https://b2a64e42.ngrok.io/lock?id=penetal%252Fatlantis_test%252Fiac%252Fmgmt%252Fatlantis%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p lab-atlantis`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by edwdev** [comment]
atlantis apply

**Comment by penetal** [comment]
Ran Apply for project: `lab-atlantis` dir: `iac/mgmt/atlantis` workspace: `default`

```diff
module.atlantis.aws_alb_target_group.app: Modifying... (ID: arn:aws:elasticloadbalancing:eu-west-1:...oup/thlarsen-atlantis/de2c264197672231)
  health_check.0.matcher: "200" => "200-499"
module.atlantis.aws_alb_target_group.app: Modifications complete after 1s (ID: arn:aws:elasticloadbalancing:eu-west-1:...oup/thlarsen-atlantis/de2c264197672231)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

Outputs:

alb_dns_name = thlarsen-atlantis.awslab.basefarm.eu
alb_hostname = thlarsen-atlantis-95695369.eu-west-1.elb.amazonaws.com
certificate_arn = arn:aws:acm:eu-west-1:552687213402:certificate/c77ae138-1089-41bd-b0b5-ff9890af5714
certificate_fqdn = thlarsen-atlantis.awslab.basefarm.eu

```

**Comment by penetal** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by penetal** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `iac/mgmt/atlantis` workspace: `default`

**Pull request merged**
